#!/usr/bin/env bash

function chruby_default() {
  if [[ -n "$CHRUBY_DEFAULT" ]]; then
    chruby "$CHRUBY_DEFAULT"
  else
    chruby_reset
  fi
}

function enter_ruby_version {
  readonly local current_dir=$1
  local version
  local gem_dir

  [[ -n "${RUBY_AUTO_VERSION}" ]] && return

  if { read -r version <"${current_dir}/.ruby-version"; } 2>/dev/null; then
    chruby "${version}"
    RUBY_AUTO_VERSION="${version}"

    if [[ -f "${current_dir}/.gemset" ]]; then
      gem_dir=${current_dir//\//\%}
      gem_dir=${gem_dir// /_}
      gem_dir="${HOME}/.gem/gemsets/${gem_dir}"
      RUBY_GEMSET="${gem_dir}"
      gem_home "${RUBY_GEMSET}"
    fi

    RUBY_AUTO_BINSTUBS="${current_dir}/.bin"
    prepend_path ${RUBY_AUTO_BINSTUBS}
  fi
}

function exit_ruby_version {
  if [[ -n "${RUBY_AUTO_BINSTUBS}" ]]; then
    remove_from_path "$RUBY_AUTO_BINSTUBS"
    unset RUBY_AUTO_BINSTUBS
  fi

  if [[ -n "${RUBY_GEMSET}" ]]; then
    gem_home -
    unset RUBY_GEMSET
  fi

  if [[ -n "${RUBY_AUTO_VERSION}" ]]; then
    chruby_default
    unset RUBY_AUTO_VERSION
  fi
}

if command_exists "chruby" && command_exists "gem_home"; then
  register_env_hook .ruby-version ruby_version
fi
