# vim: set ft=ruby:

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "chruby"
brew "coreutils"
brew "ctags"
brew "dos2unix"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "brew_formulae/gem_home.rb", args: ["HEAD", "build-from-source"]
brew "gh"
brew "gist"
brew "git"
brew "graphviz"
brew "grep"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jq"
brew "leiningen"
brew "llvm"
brew "netcat"
brew "openjdk"
brew "parallel"
brew "pkg-config"
brew "plantuml"
brew "pre-commit"
brew "pv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby-install"
brew "rustup"
brew "shellcheck"
brew "shunit2"
brew "sloccount"
brew "swi-prolog"
brew "tcpflow"
brew "tfenv"
brew "tmux"
brew "tree"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"

cask_args appdir: "/Applications", require_sha: true

cask "1password" unless ENV['JAMF']
cask "alfred"
cask "bluesnooze"
cask "evernote"
cask "flux"
cask "iterm2"
cask "session-manager-plugin"
cask "shiftit"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
